controller_port = 0
gyro_port = 0

[motors]
front_right_port = 1
front_left_port = 2

rear_right_port = 3
rear_left_port = 4


[motors.shooter.pid]
P = 0.1
I = 0
D = 0

[motors.shooter]
port=6

[motors.turret]
port = 7

[motors.turret.pid]
P = 0.05
I = 0
D = 0

[motors.intake]
port = 8

[motors.intake.pid]
P = 0.05
I = 0
D = 0


[vision]
camera_name = "main"